name: memoize
description: Memoization function for dart
version: 1.0.0

authors:
- Alexander Polyankin <alexander.polyankin@team.wrike.com>
- Max Grebenschikov <maxim.grebenshikov@team.wrike.com>

homepage: https://github.com/wrike/memoize_dart

environment:
  sdk: '>=1.21.1 <2.0.0'

dependencies:
  func: ^0.1.1

dev_dependencies:
  test: ^0.12.15+2
